### PR TITLE
color logs

### PR DESCRIPTION
**Pull request by pratik-prajapati-imgtec**
error - red
info  - cyan
debug - white

Signed-off-by: Pratik Prajapati <Pratik.Prajapati@imgtec.com>

### CODE REVIEW

**Comment by mayank-sirotiya-imgtec** [comment]
Approved

**Comment by abhijit-mahajani-imgtec** [comment]
Approved

**Comment by nikhil-zinjurde-imgtec** [comment]
Verified failed, logs are displayed correctly with 'cat' command, but not with 'vi' command

**Comment by nikhil-zinjurde-imgtec** [comment]
Verified +1

**Pull request closed without merging**
